FROM apache/spark:3.5.0

USER root

COPY jars/hadoop-aws-3.3.4.jar /opt/spark/jars/
COPY jars/aws-java-sdk-bundle-1.12.262.jar /opt/spark/jars/
COPY jars/spark-sql-kafka-0-10_2.12-3.5.0.jar /opt/spark/jars/
COPY jars/kafka-clients-3.4.0.jar /opt/spark/jars/
COPY jars/spark-token-provider-kafka-0-10_2.12-3.5.0.jar /opt/spark/jars/
COPY jars/commons-pool2-2.11.1.jar /opt/spark/jars/
COPY jars/postgresql-42.7.3.jar /opt/spark/jars/

USER spark