services:
  eventsim:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: eventsim_generator
    # network_mode: host
    restart: "no"
    mem_limit: 5g
    cpus: 5
    memswap_limit: 5g

    volumes:
      - ./data:/opt/eventsim/data
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f eventsim || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    command: >-
      -c examples/example-config.json
      --kafkaBrokerList kafka:9092

      --nusers 100
      --growth-rate 1
      --start-time 2026-03-01T00:00:00
      --end-time 2026-03-10T00:00:00
      --userid 1
      --randomseed 1
    depends_on:
      - kafka 
  
  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: exbDrwnPTlqim7-51SwxYw

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    volumes:
      - kafka-data:/home/xuanhoang/docker/volumes/eventsim_kafka-data/_data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
networks:
  default:
    name: eventsim-network

volumes:
  kafka-data: