services:
  eventsim:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: eventsim_generator
    # network_mode: host
    restart: unless-stopped
    mem_limit: 6g
    cpus: 6
    memswap_limit: 10g

    volumes:
      - ./data:/opt/eventsim/data

    command: >-
      -c examples/example-config.json
      --continuous
      --nusers 1000
      --growth-rate 1
      --start-time 2020-03-01T00:00:00
      --end-time 2026-03-10T00:00:00
      --userid 1
      --randomseed 1
    depends_on:
      - kafka 
  
  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: exbDrwnPTlqim7-51SwxYw

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  default:
    name: eventsim-network